### ISSUE TITLE
libedit: consider merging a segfault patch

### ISSUE THREAD

**Issue by asiekierka** [sabotage-linux/sabotage#234]
I specifically say "consider" because, according to the original bug report about it, there is nothing in common between the machines it appeared on.

Explanation: http://bugs.mysql.com/bug.php?id=58497
Patch: https://github.com/asiekierka/yuyulinux/blob/master/libedit/libedit-buffer-fix.patch

**Comment by asiekierka** [comment]
I quite honestly can't remember. It *might* have been gdb.

**Comment by rofl0r** [comment]
closing this until the issue can be reproduced.
