### ISSUE TITLE
Go download URL redirects to https, busybox wget fails

### ISSUE THREAD

**Issue by jprjr** [sabotage-linux/sabotage#252]
Hi there -

It looks like the download URL for go redirects to an HTTPS link, causing wget to fail.

I tried looking into somehow specifying in the package's config file that you need an SSL-enabled wget, but I'm not sure if that's possible.

I think the workaround is to just download the file manually and place it in the right spot (I'm trying that right now as I type this).

**Comment by rofl0r** [comment]
for the record: this was properly fixed now.
we added a patch for busybox, that, if an openssl binary is available, enables its wget to do https, and documented in the README that it is necessary to build stage2 instead of stage1 if https support is required.
