### ISSUE TITLE
Sabotage as desktop linux for x86_64

### ISSUE THREAD

**Issue by r004** [sabotage-linux/sabotage#294]
;)
I want to install sabotage for my dsktop box. it is an amd64 arc and I need to know if it is going to work.
It is nice to know from where to start.
thanks
/=======
lightwight setup
wmfs
alsa
mplayer
a file manager
python
/=======

**Comment by henriqueleng** [comment]
On Sun, Jan 25, 2015 at 01:23:10PM -0800, _root_ wrote:
> ;)
> I want to install sabotage for my dsktop box. it is an amd64 arc and I need to know if it is going to work.
> It is nice to know from where to start.
> thanks @rofl0r 

Hi, and welcome!
So first, have you ever had any experience with linux before? If yes, you are prepared to use
sabotage. And also, your computer should be supported by it.

Normally if you can run other linux in your computer, you will be able to run sabotage linux.
It is easy to run almost anything on it, so I think you can thrust. As there is not many people
using it, sometimes you can find a bug, a problem or some feature that no one yet implemented,
(like the PKGBUILD of a software, or some software may be out of date) and you will need to solve it. 
So if you can't or don't want to sometimes need to search on the internet or ask someonte to have
some software installed, I think its not time to you use sabotage. Maybe in the future if we have more 
people to work to set the things, sabotage will be accessible to everyone.

But by default things should work pretty well, and you should be able to install and use all the softwares
of the pkg folder, and compile any other if you want.

Regards.

Henrique Lengler

**Comment by r004** [comment]
;) Henrique;
I did my fair share of installing gentoo, chrooting and compiling kernels. so I think I could star with your sabotage.
the thing is I am not sure how to start. should I clone the repo and chroot into it or what. then what is the next step?
if you could give me a list of steps I need to take and their order!
;)

**Comment by henriqueleng** [comment]
On Sun, Jan 25, 2015 at 04:11:59PM -0800, _root_ wrote:
> ;) Henrique;
> I did my fair share of installing gentoo, chrooting and compiling kernels. so I think I could star with your sabotage.
> the thing is I am not sure how to start. should I clone the repo and chroot into it or what. then what is the next step?
> if you could give me a list of steps I need to take and their order!
> ;)

It is very simple. Clone the repo https://github.com/sabotage-linux/sabotage.git;
Enter the folder and start following these instructions: https://github.com/sabotage-linux/sabotage/blob/master/README.md#native-build-instructions
Above instructions will give you a folder with your new system, so now you need to copy this files to a formated/partitioned disk,
you can do this by entering any live system, and do the work by there.
If you need to do a different thing like compile your own customized kernel, or install the system in a UEFI bios. You can get information
in existing threads in the mailing list (You should also subscribe to it) http://openwall.com/lists/sabotage/.
Read the README and the COOKBOOK will give you all the thing you want.

Good Luck,

Henrique Lengler

**Comment by soul9** [comment]
there is also a wiki [here](https://github.com/sabotage-linux/sabotage/wiki) to help you

**Comment by henriqueleng** [comment]
soul9, Could you please check the patches I updated in the mailing list? It fixes Xorg with intel
drivers. Looks like there is no one more reading the mails there.
The links: http://openwall.com/lists/sabotage/2015/01/10/1
and the most important: http://openwall.com/lists/sabotage/2015/01/09/1
Now that I created a github account I will be able to send you the patches directly, but I can't
recover these that are in the mailing list.

**Comment by JillTyrell** [comment]
Henrique, you're expected to read the documentation around here. From the documentation:

> it is necessary that you create git branches for your work: this allows me to checkout your changes and rebase as i see fit, and you can easily pull back into your master without getting merge conflicts.

rofl0r hasn't been accepting random diffs posted willy nilly for ages now. Fork the repo, make a feature branch and submit a PR like the rest of us.

**Comment by henriqueleng** [comment]
On Mon, Jan 26, 2015 at 04:46:57PM -0800, Jill Tyrell wrote:
> Henrique, you're expected to read the documentation around here. From the documentation:
> 
> > it is necessary that you create git branches for your work: this allows me to checkout your changes and rebase as i see fit, and you can easily pull back into your master without getting merge conflicts.
> 
> rofl0r hasn't been accepting random diffs posted willy nilly for ages now. Fork the repo, make a feature branch and submit a PR like the rest of us.

This is a git formated patch that he told me to do. Because in this time I had no github account so I was sending patches by email. He accepted a lot of them.
https://github.com/sabotage-linux/sabotage/commit/5a24cb6c4afc75d4f20714236c1333362787f762
https://github.com/sabotage-linux/sabotage/commit/2bde57c50ffc1d53b003c0460902939af600a84c
https://github.com/sabotage-linux/sabotage/commit/f214a91c1f3117ff14b48d3cc017d6a6dbbd9794
https://github.com/sabotage-linux/sabotage/commit/63c975c78ff44bb00030217a2a42fdca677477ca
https://github.com/sabotage-linux/sabotage/commit/f99698fc516232e27ea3d1eacd35af9b24dfe451

**Comment by henriqueleng** [comment]
Since I will probably get no help, I will send the patches by github

**Comment by henriqueleng** [comment]
Can't I send a pull-request directly by git? I need help.
I did a git checkout -b to create a branch. In this branch I added all the patches.
Now I want to push and add a pull-request but I can't, could someone help me?

**Comment by henriqueleng** [comment]
Looks like I need to fork before

**Comment by henriqueleng** [comment]
I think this should be closed
