### ISSUE TITLE
rc.local is becoming bloat

### ISSUE THREAD

**Issue by soul9** [sabotage-linux/sabotage#312]
I think a lot of the stuff in rc.local should be made more robust (especially networking stuff) and most of it should go in service scripts

**Comment by rofl0r** [comment]
pls elaborate

**Comment by soul9** [comment]
well, for example the dhcp problem I am having: on some machines dhclient has to be run twice to obtain an ip, and I nom have a machine where it only works thrice. And static configuration seems to suffer from the same issue. If you want to make *sure* you get an ip, status should be checked and configuration verified, which is too complex to put in rc.local, so a networking service could be used for this purpose.
