### ISSUE TITLE
Resolved:: Sabotage is stable w/ Linux Kernel 3.19.4  _and_ 4.1.0rc3

### ISSUE THREAD

**Issue by bitshark** [sabotage-linux/sabotage#317]
I recompiled the kernel for Sabotage Linux out of necessity.... the stock kernel did not include the appropriate framebuffer drivers for my laptop (i915.ko Intel based)...  (Dell Inspiron 17r laptop)

But here's the good news:  The 3.19.4 kernel compiles fine, no problems, and I will issue pull requests for (A) the kernels and (B) my XFCE build and LXQT build as soon as I finish testing (perhaps as an option -- certainly not the default).   The 3.19.4 kernel made X work properly, but it did have issues related to IRQ interrupt problems w/ the Intel i915 driver -- specifically in i915_irq.c.    X would start, but system unstable generally.

After this problem (a kernel issue), I reviewed the kernel mailing list, and it seems that the ' buggy intel' drivers are responsible...  The bug is old, but reappeared in the 3.x kernel series on and off. ..  the intel i915 bugs appear fixed in the 4.1 kernel...   I decided to give the new 4.1 kernel a shot -- and it works great!

All drivers work, eudev works, X works, and so forth. 

Summary:  On Sabotage, X was hard to get working in X with stock kernel.  There were mainly Intel Driver issues.... These issues got worse in some ways with kernel 3.19 (which added IRQ conflict bugs).... All issued were resolved with an upgrade to kernel 4.1.

Below is an example of the "IRQ" bug present on Sabotage with kernel 3.19 ... The origin is the kernel code, specifically the Intel video chipset having some sort of bug when sharing IRQs with other devices.

The issue here can probably be marked closed -- the details are included here in case anyone else runs into the issue on Sabotage or another distro.

### Dmesg Error on Sabotage Linux w/ Kernel 3.19 (Intel i915)
------------[ cut here ]------------                                                              
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704204] WARNING: CPU: 3 PID: 3496 at drivers/gpu/drm/drm_irq.c:1130 drm_wait_one_vblank+0x10e/0x16c()     
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704206] vblank wait timed out on crtc 0                                                                   
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704207] Modules linked in: xfs x86_pkg_temp_thermal vmxnet3 vmwgfx vmw_pvscsi virtio_scsi virtio_blk vfat 
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704240] CPU: 3 PID: 3496 Comm: X Tainted: G        W      3.19.4 #1                                       
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704241] Hardware name: Dell Inc.          Inspiron 5720/023HTX, BIOS A19 04/18/2014                       
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704243]  0000000000000000 0000000000000009 ffffffff816e38c6 ffff8801b6d5bb48                              
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704245]  ffffffff81090c4a ffff8801b81c8000 ffffffff813c17a4 ffff8801b81c8000                              
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704247]  0000000000000000 ffff8801b80c6000 0000000000000000 00000000000410a6                              
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704249] Call Trace:                                                                                       
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704256]  [<ffffffff816e38c6>] ? dump_stack+0x40/0x50                                                      
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704259]  [<ffffffff81090c4a>] ? warn_slowpath_common+0x93/0xab                                            
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704262]  [<ffffffff813c17a4>] ? drm_wait_one_vblank+0x10e/0x16c                                           
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704264]  [<ffffffff81090cfa>] ? warn_slowpath_fmt+0x45/0x4a                                               
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704268]  [<ffffffff810b738c>] ? prepare_to_wait_event+0xb0/0xec                                           
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704271]  [<ffffffff813c17a4>] ? drm_wait_one_vblank+0x10e/0x16c                                           
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704274]  [<ffffffff810b768f>] ? add_wait_queue+0x3b/0x3b                                                  
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704278]  [<ffffffff81421507>] ? intel_pipe_set_base+0x1a2/0x1e4                                           
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704281]  [<ffffffff8142ad68>] ? intel_crtc_set_config+0x7fd/0xb4c                                         
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704285]  [<ffffffff8130ca1f>] ? idr_alloc+0x91/0xbc                                                       
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704288]  [<ffffffff813c7ade>] ? drm_mode_set_config_internal+0x4e/0xd2                                    
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704291]  [<ffffffff813cb63c>] ? drm_mode_setcrtc+0x3e9/0x48e                                              
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704294]  [<ffffffff813c046f>] ? drm_ioctl+0x279/0x3bc                                                     
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704296]  [<ffffffff813cb253>] ? drm_mode_setplane+0x1e4/0x1e4                                             
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704300]  [<ffffffff8113a4d0>] ? do_vfs_ioctl+0x412/0x459                                                  
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704304]  [<ffffffff8114190c>] ? put_unused_fd+0x1e/0x3d                                                   
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704306]  [<ffffffff8113a560>] ? SyS_ioctl+0x49/0x77                                                       
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704310]  [<ffffffff816e9176>] ? system_call_fastpath+0x16/0x1b                                            
May 13 03:03:35 localhost kern.warn kernel: [ 4428.704312] 
---[ end trace 7f00169d79dfaaae ]---         
'''

**Comment by rofl0r** [comment]
closing this as we have a 4.x kernel now.
