### ISSUE TITLE
login: can't set groups: Function not implemented

### ISSUE THREAD

**Issue by henriqueleng** [sabotage-linux/sabotage#356]
In my first boot of sabotage, I can't log in... I get:
login: can't set groups: Function not implemented
if I type the right password. 
Tried to change the password in a chroot, but it don't work.
Any idea about what is causing the error?

**Comment by rofl0r** [comment]
sorry for the inconvenience, but you need to add
CONFIG_MULTIUSER=y to the kernel config and rebuild the kernel.
this is a new kernel "feature" that breaks existing configs...
