### ISSUE TITLE
Missing CONFIG_LBDAF in KEEP/linux.conf

### ISSUE THREAD

**Issue by renjithis** [sabotage-linux/sabotage#368]
I'm a bit new to Sabotage, but after compiling and creating virtualbox image with instructions provided (on Ubuntu 14.04 32 bit), / was getting mounted read-only. This was without any config change (/boot/extlinux.conf said rw). 

dmesg had an error saying Fileystem with huge files cannot be mounted RDWR without CONFIG_LBDAF

Searching for it revealed that at one time it was added to linux.conf (which closed a ticket witht he same error) : e96c89512ae4fde6dd57133d00a7c3db8352a425 , but was removed when linux.config's options were grouped (for readability i'm guessing) in commit : 715b9cd211fedcfe7b95630f764cde63202c785c

Was this intended? if so, how do I resolve my error?

**Comment by rofl0r** [comment]
it seems it was removed by mistake (and nobody noticed because everyone uses 64bit)

please open a PR that reenables the config item, thanks!

**Comment by renjithis** [comment]
Hi again,

I will surely do that, but I will need some help. Can you tell me under which comment section it should go to. I am a bit new to contributing to an open-source project. Sorry for the noobness

**Comment by henriqueleng** [comment]
If I remember correctly this another problem, you should specify you root partition and set it 'rw' either on kernel command line or on the bootloader

**Comment by rofl0r** [comment]
you could go into make menuconfig, enable the option manually (by searching for it), and then see where the kernel puts it
