### ISSUE TITLE
php build fails

### ISSUE THREAD

**Issue by bkauler** [sabotage-linux/sabotage#418]
Hi,
I went through all the steps in the readme, from cloning the repo, right up to running "butch install world", for x86_64.

It completed, except for two build fails, php and mysql.

Here is the build log for php:
[build_php.log.txt](https://github.com/sabotage-linux/sabotage/files/244399/build_php.log.txt)

**Comment by liwakura** [comment]
Could not reproduce as of Oct 2016. Probably fixed with f6e67c72.

**Comment by rofl0r** [comment]
good catch. closing this.
