### ISSUE TITLE
libuuid and libblkid

### ISSUE THREAD

**Issue by bkauler** [sabotage-linux/sabotage#422]
I notice that libuuid is obtained from e2fsprogs, and libblkid from util-linux.

I was wondering if there is a particular reason for doing this?

Most distros are using both libuuid and libblkid from util-linux, I think because it is the more active project.

**Comment by bkauler** [comment]
Probably shouldn't have typed "most distros", can't be sure of that!

**Comment by rofl0r** [comment]
its because e2fsprogs is part of stage1, so its available early and because it works.
