### ISSUE TITLE
bkauler/sabotage restructured to not conflict

### ISSUE THREAD

**Issue by bkauler** [sabotage-linux/sabotage#424]
rofl0r,
Just to let you know, I have restructured bkauler/sabotage so that my changes do not conflict with sabotage-linux/sabotage, so you can do a pull from there if you wish.

I am doing something very interesting, compiling packages to build Quirky Linux or Puppy Linux. I am the creator of Puppy Linux, back in 2003, after 10 years handed over maintenance to the "Puppy community". I still have a plaything, Quirky Linux, forked from Puppy, where I try new ideas.

Puppy/Quirky is a chameleon, uses the build system Woof (WoofCE or WoofQ), which will build a distro from the binary packages of any other distro.

What I am doing now is compiling those packages in Sabotage, which could simply be imported into Woof. However, I am looking further, at a merge with Sabotage, adopt the file hierarchy, butch, etc.

For Quirky, I do have some different requirements than Sabotage. For example, Quirky has cutdown util-linux and coreutils, replacing some of the busybox applets. util-linux also provides both libblkid and libuuid.
To avoid conflicts, I have named my alternative packages pkg/qky-*, for example, pkg/qky-e2fsprogs.
To provide build-time changes, I have pkg/qky-customize -- currently all that does is change pkg/libblkid and pkg/libuuid at build-time.

So, my changes do not conflict with the main Sabotage, and if you wish, you can pull them from bkauler/sabotage, or if you would rather not, that's ok too.
Of course, I am introducing new packages, just a few so far (asunder, f2fs-tools, x264, x265, etc), but it is going to become a flood, so you might want those.

**Comment by bkauler** [comment]
rofl0r,
Regarding your response to my accidental pull request #423, now closed (being new to git, I got it the wrong way round).
There is no problem with pulling from sabotage-linux/sabotage master to bkauler/sabotage master, I have already done that a couple of times.
My restructuring ensures that this works, no conflicts.

**Comment by rofl0r** [comment]
barry, my consideration was not that you cannot merge from sabotage/master, but that *i* cannot merge from yours, because doing so would spam the commit history with ugly merge commits.

**Comment by bkauler** [comment]
Fair enough. I don't have enough experience yet with Sabotage (and git).

**Comment by rofl0r** [comment]
that is possible, however it would be nice if we could integrate some of the packages you made also in here. but don't worry, in the worst case we can just copy the pkg files you made, and add them one after the other to a branch equal with sabotage/master. the details can be discussed later, it's nice to see that you're making progress with git.
