### ISSUE TITLE
butch-core script versus compiled

### ISSUE THREAD

**Issue by bkauler** [sabotage-linux/sabotage#425]
Could someone kindly explain what is happening here?
Is KEEP/bin/butch-core going to replace the C compiled version?

Currently, although KEEP/bin/butch-core exists, the butch C package is still compiled and used.

**Comment by rofl0r** [comment]
yes, we're just discussing in the IRC channel how we clean that up - see #426
and yes, it looks like we keep the new shell version, since it proved to be fast (note that you need jobflow for full parallel download speed, but that will be integrated into stage0

**Comment by rofl0r** [comment]
please let me know how the script version works for you and if you're satisfied with its speed.

**Comment by bkauler** [comment]
I like the idea of the shell version, if it is fast. 
The shell version is broken though, I posted another issue, #427
