### ISSUE TITLE
build-stage0 now broken

### ISSUE THREAD

**Issue by bkauler** [sabotage-linux/sabotage#427]
On my local system, after the last commit of butch-related changes, running "./build-stage0" is broken.
It outputs two lines, then the next, if I recall rightly, to build butch, never happens, it just hangs, very little cpu activity.

I reverted all the butch-related pulls, right back to "add shell implementation of butch-core", and now build-stage0 is working again.

Ah, I still have it in my terminal. Here is what happened when it hung:

```
# ./build-stage0 
2016-05-06 15:46:13 initializing root system
2016-05-06 15:46:13 installing stage0
```
...then hang

After reverting:

```
# ./build-stage0 
2016-05-06 15:53:38 initializing root system
2016-05-06 15:53:38 building butch
2016-05-06 15:53:41 installing stage0
*** downloadqueue ***
gcc3
stage0-musl
kernel-headers
```
...etc
...working

**Comment by rofl0r** [comment]
i noticed that you were missing this commit earlier https://github.com/sabotage-linux/sabotage/commit/d37951100640e9562c5d7803e39500bef4e5628f

**Comment by bkauler** [comment]
Yes, that fixed it!

I started from scratch, have now completed stage1. No problem with the new butch.

It is good that it is a script, as I want to put a little build-time patch into it. I want to be able to put something into a recipe to tell butch-core not to update butch.db.

The reason is, I have package recipes named "qky-*", for example "qky-e2fsprogs", so as not to conflict with your e2fsprogs recipe. However, my recipe installs it as e2fsprogs, well nearly, except for butch-core writing qky-e2fsprogs entry to butch.db.

I thought one way to fix it is to have a variable in src/config, with alternate package names, like "qky_util_linux=util-linux", that update_butchdb() in butch-core can read and substitute, in this example "util-linux" when writing to butch.db.
Not sure how to code that.

An alternative is that the [build] recipe for qky-util-linux could write "util-linux" into a file, say "$R"/tmp/qky-util-linux. update_butchdb() can read that file if it exists, and write the alternative name to butch.db.

...seems like a hack solution, can't think of anything more elegant. This doesn't necessarily have to be in your master, I could patch butch-core at build-time.

**Comment by bkauler** [comment]
OK, I have refined the hack. I have pkg/quirky-customize, which does some little hacks. I added this into the [build]:
```
#my alternative pkgs all have "qky-" prefix, ex 'qky-util-linux' installs as
# 'util-linux', need this for butch-core:
sed -i -e 's%mv $BUTCHDB.tmp $BUTCHDB%sed -e "s/^qky-//" $BUTCHDB.tmp > $BUTCHDB%' "$R"/opt/butch/bin/butch-core
```
It is a simple little hack for butch-core, so all my qky-* recipes get registered in butch.db without the "qky-" prefix.
Other stuff, like filelist and installing without the qky- prefix in /opt, are taken care of in the recipes.

**Comment by rofl0r** [comment]
in case you wonder where /opt etc come from, take a look at the build template in KEEP (butch-template....txt) (hint: it is customizable, at least theoretically)
