### ISSUE TITLE
butch download fails

### ISSUE THREAD

**Issue by bkauler** [sabotage-linux/sabotage#428]
I have an alternative recipe for busybox, that I have named pkg/qky-busybox, with:

[mirrors]
https://busybox.net/downloads/busybox-1.24.2.tar.bz2

However, "butch download qky-busybox" fails. 
The certificate is wrong. I encountered this situation before, and it still downloaded. I suppose before, it stuck in the "--no-check-certificate" for wget.

**Comment by rofl0r** [comment]
no, old and new butch-core used the same download template (KEEP/butch_download_template.txt). i suspect you previously used a non-https url?

**Comment by bkauler** [comment]
Yeah, I must be remembering it wrong.
