### ISSUE TITLE
xf86-video-nv build fail, fix

### ISSUE THREAD

**Issue by bkauler** [sabotage-linux/sabotage#432]
Needs a patch:
https://github.com/bkauler/sabotage/commit/3413688fba2e18944f100b2f660b6d9566d583f1

**Comment by rofl0r** [comment]
thanks d3461e6

would be easier for me if you could provide these things as pull requests against master
something like git checkout official/master ... git checkout -b branch_for_fix_for_foo ... do work ... git commit ... open pull
