### ISSUE TITLE
gettext versus gettext-gnu

### ISSUE THREAD

**Issue by bkauler** [sabotage-linux/sabotage#433]
Hi, I need some advice thanks. I am new to using musl, so unfamiliar with the problems with gnu gettext.

I have a build with the 'gettext' package, however 'xgettext' is a stub. 
I have some source packages that run xgettext to extract .pot files from C source.

I presume that there are problems with using the gnu gettext, but I was wondering if I could just use the 'xgettext' utility from it? Would there be any problems with doing that?
It would be easy to compile statically, it only has libc shared lib on my host system.

**Comment by rofl0r** [comment]
we found gnu gettext to be incredibly bloated (more than an hour build time on my arm netbook) and thus decided to create a replacement, that works by just outputting the original text as the translation, i.e. english only. if you have an example of a package that fails with the gettext-tiny xgettext implementation, please provide more details so we can fix xgettext. (but yes, gettext-gnu should work as well).

**Comment by bkauler** [comment]
In gettext-tiny, utility 'xgettext' is a stub, does nothing. It is just a small shell script that responds to --help, nothing else.
I don't know anything about this, but glancing through some forums, there is discussion about problems with gnu gettext and musl, and someone recommended using a very early version of gnu texttext.

So I did, I compiled the earliest version of gnu gettext that I could find, 0.10.40, released in 2001. It compiled, and xgettext works. I have used it in three sources packages.

It compiled very fast. Um, how long... just doing it again on my desktop... 15 seconds.

My recipe is here: https://github.com/bkauler/sabotage/commit/8e6a25e4b107b03a283f3090d59a5b371d2fcb0d

**Comment by rofl0r** [comment]
the stub xgettext seemed to work fine so far, especially when disabling NLS via --disable-nls on configure-type packages. judging from the commit you linked the xgettext utility is used only by some of your custom panel applets ? if it is a hard requirement to make these translation files, maybe you could consider creating them beforehand and including them in your release tarballs. let me know if you encountered any regular packages that fail to build with tiny-gettext.

**Comment by bkauler** [comment]
I found that gnu gettext 0.10.40 is too old. To translate many shell scripts, that are used in Puppy Linux and Quirky Linux, the utilities xgettext.sh and ngettext are required, not in that old version.
I settled on gnu gettext version 0.13.1, released in 2003. It has all the utilities, and compiles very fast (can't recall exactly, it was under a minute). Also it is very small -- about 5M gzip tarball, and I think the latest is about 13M xz tarball.
Another good thing, it compiled in sabotage right-off. I did try 0.14.x, got compile errors.

Right now I am doing a complete compile, with the abovementioned gnu gettext instead of gettext-tiny, and ncurses instead of the bsd curses. Oh yeah, also rolled libpng back to 1.2.56. So far, so good...

**Comment by bkauler** [comment]
My complete recompile ran into a problem. Package glib failed, msgfmt didn't like the content of one of the .po files. This would be due to it being such an old version.
I got around it by bringing back gettext-tiny, just the two utilities msgfmt and msgmerge.
glib was then happy. Oh, yeah, I also used libintl.a from it, rather than the one in gettext-gnu.

**Comment by bkauler** [comment]
Looking at the source, xgettext.sh is a shell script, that gets renamed to xgettext at installation:

https://github.com/sabotage-linux/gettext-tiny/blob/master/src/xgettext.sh

It does nothing. All it does is create an empty .po file. 
Correcting an earlier comment, for translating shell scripts, I need gettext.sh and ngettext. The latter is a binary executable. gettext.sh is different from xgettext[.sh]
These two are provided by gnu gettext. 
For generating .pot files from some C sources, I need xgettext binary executable from gnu gettext.

Right now I seem to have hit the sweet spot, got everything right, regarding gettext and libintl.a anyway, and doing a recompile.
Haven't pushed the latest local fixes, as right now have an issue with my online git repo, see my last issue post.
