### ISSUE TITLE
Butch patching bug

### ISSUE THREAD

**Issue by bkauler** [sabotage-linux/sabotage#435]
I am hitting these butch errors after the last pull #4 from sabotage-linux to bkauler.

I have my own util-linux recipe, with one patch:

`patch -p1 < "$K"/util-linux-fix-nls-disabled.patch`

The build log:
```
Tue May 17 07:34:42  2016: start build
patching file include/nls.h
Hunk 1 FAILED 13/13.
 #  define N_(String) (String)
 # endif
 #else
+# include <locale.h>
 # undef bindtextdomain
 # define bindtextdomain(Domain, Directory) /* empty */
 # undef textdomain
```
However, the patch is OK. It worked before, and when I test it manually on the source, it works.

**Comment by bkauler** [comment]
Ah, I can close this one. I left out 'patch' package, and it was using busybox patch.
Did some experimenting, busybox patch works with some patches, not all.

**Comment by rofl0r** [comment]
yeah, busybox patch is broken when patches need fuzzing (i.e. the line number has changed).
