### ISSUE TITLE
Git confusion

### ISSUE THREAD

**Issue by bkauler** [sabotage-linux/sabotage#437]
I did a pull from sabotage-linux a few days ago: 
https://github.com/bkauler/sabotage/commit/6a5d705b13bdbd0a955054f66b040141e1b49beb

However, I reverted it:
https://github.com/bkauler/sabotage/commit/ed03c430dbbb5cec6fc6494920f861fb1d60b955

Shouldn't have done that! Haven't got a clue how to "unrevert" it.
I looked at doing a pull from sabotage-linux, but it seems to be leaving out those earlier reverted changes.

Can you give any advice?

**Comment by rofl0r** [comment]
maybe ```git revert ed03c430dbbb5cec6f```

**Comment by bkauler** [comment]
Ah, yes, found out how to do that in the github GUI. Thanks.
