### ISSUE TITLE
Typo in many recipes

### ISSUE THREAD

**Issue by bkauler** [sabotage-linux/sabotage#438]
My latest recompile is progressing well, however I have encountered the same bug in many packages, that causes a compile failure. For example, geany has this line:

`printf 'all:\n\ttrue\ninstall:\n\ttrue\clean:\n\ttrue\n' > po/Makefile`

Between "true" and "clean" there should be a newline, preferably two:

`printf 'all:\n\ttrue\ninstall:\n\ttrue\n\nclean:\n\ttrue\n' > po/Makefile`

This same typo has been pasted into a lot of packages.

**Comment by rofl0r** [comment]
interesting that i never encountered this compile error. do you use another version of make ? please provide a log of the exact error you're getting.

**Comment by bkauler** [comment]
I don't have to provide an exact log, it is obviously wrong. The Makefile gets generated like this, before I fixed it:
```
install:
    true\clean:
    true
```
Which is a broken syntax, and compile failed on that line "true\clean". I don't know why this wasn't picked up before. I am using the same make.
It should be:
```
install:
    true
clean:
  true

```

**Comment by bkauler** [comment]
Ah, I think I know why you didn't hit the problem. I have /bin/sh a symlink to bash, and printf is in-built to bash. 

Trying it with busybox printf:
```
# busybox printf 'all:\n\ttrue\ninstall:\n\ttrue\clean:\n\ttrue\n'
all:
	true
install:
	true#
```
Which is correct syntax for a Makefile, but a wrong result.

**Comment by rofl0r** [comment]
> Which is correct syntax for a Makefile, but a wrong result. 

wrong result in which regard ?

**Comment by rofl0r** [comment]
oh i see. i actually misread your earlier text and didnt notice that the printf statement also had a clean target in it.
