### ISSUE TITLE
bacon: want to avoid running wget during build

### ISSUE THREAD

**Issue by bkauler** [sabotage-linux/sabotage#444]
In my recipe for package bacon (a BASIC compiler, allows creation of GUI apps), I run wget a couple of times, to download some extra needed files. For example:
```
#grab some more stuff. unfortunately, can't build off-line!
#HUG Highlevel Universal GUI library...
wget http://www.basic-converter.org/hug.bac
mkdir temp1
if $butch_do_custom_destdir ; then
 #need to install lib so bacon can find it...
 ln -sf "$dest"/lib/libbacon.a "$R"/lib/libbacon.a
fi
./build/bacon -d temp1 -f hug.bac -o '-fPIC'
cp -a -f temp1/hug.so "$dest"/lib/
```
I would like to put that into a separate package, say 'bacon-hug-lib', so can download before the main build.

The problem is, that "hug,bac" file will keep changing. It is just the latest, the developer does not keep versioned copies of it.

In the T2 project, this situation can be handled by specifying a value of zero for the checksum, meaning, just accept the file as-is.
So, in [vars] we would have:
```
filesize=0
sha512=0
```
Not very satisfactory, but I can't think of any other way to handle it.
Unless I create versioned copies myself and upload them somewhere.
Do you have any thoughts on this?

**Comment by rofl0r** [comment]
we could change the download template such that it emits sha512 check when the sha512 variable is unset/empty (same for filesize) - maybe it even does that already.
HOWEVER, this makes it impossible to make a reproducible build - a user that builds the exactly same system an hour later might already get a different result.
so optimally this could be fixed upstream - for example you might propose to bacon's author that he puts these .bac files in a github repo, so you can download a specific version using the commit's hash.

**Comment by bkauler** [comment]
I have solved it by creating a tarball. There are actually four files, so I stuck them into a tarball, bacon-runtime-3.2.2.tar.gz, and I have created a new recipe, bacon-runtime:
https://github.com/bkauler/sabotage/commit/737c45d983736ca455f94376760722c4797646c1
