### ISSUE TITLE
linux manpages missing

### ISSUE THREAD

**Issue by rofl0r** [sabotage-linux/sabotage#462]
afaik the linux manpages is actually a mix of linux manpages (like bootparam(7)) and libc interfaces (glibc specific). since we use musl the libc interfaces are sufficiently well documented by the posix-man package. it would be nice if there was a way to install only the linux specific portion of the linux manpages tarball.

**Comment by liwakura** [comment]
As discussed in IRC, the current status of the issue is to skip the sections 1-3 of the manpages, since they are redundant and their posix equivalent (package `posix-man`) yields the same information, without being glibc specific.

**Comment by rofl0r** [comment]
yeah. do you feel like you want to add it ? maybe we can add a hook into the pkg so if a magic env var is set (for example WANT_GLIBC_MANPAGES=1) the 1-3 sections get installed as well.

**Comment by liwakura** [comment]
Added with #473
