### ISSUE TITLE
Make butch an separate package

### ISSUE THREAD

**Issue by liwakura** [sabotage-linux/sabotage#476]
Advantages:

- Butch can be easily used for other things beside sabotage (Like the config management Jill has)
- pkg tree will be easily swappable
- separate commit histories (build system changes vs recipe changes)

**Comment by rofl0r** [comment]
we actually had that before. so let me document the
Disadvantages:
- every minor update to butch required to make either a new release (make git tag, make release tarball, upload tarball), or to put patches into the sabotage tree
- you cannot call any butch script out of KEEP and be 100% sure that that has the right version

**Comment by liwakura** [comment]
But this way its messy to use butch for other things beside sabotage.
Personally, i plan to make customized recipe collections for stuff.

**Comment by rofl0r** [comment]
so what is your suggestion about how to / where to maintain butch and its integration into sabotage ?

**Comment by liwakura** [comment]
what about creating an own subdir in KEEP, so butch can easily be extracted (copied out) from sabotage, while still being available in the main repo and be part of the sabotage-core or butch package (which itself just copies stuff from KEEP/butch)
