### ISSUE TITLE
Clean up KEEP

### ISSUE THREAD

**Issue by liwakura** [sabotage-linux/sabotage#477]
TODO: Check which files in KEEP are obsolete and can be safely removed (like, C Butch patches or some of the linux configs)

**Comment by rofl0r** [comment]
idea: a script that does git log for all files there, and then for each commit id see what other files were touched (git log -p commitnr) and then output the name as a possible candidate if one of those files does not exist anymore

**Comment by rofl0r** [comment]
i think this can be closed, i removed the C butch patches, and @JillTyrell said in IRC that she already cleaned up everything apart from that.
