### ISSUE TITLE
XML Parser perl module is required for xkeyboard-config to compile

### ISSUE THREAD

**Issue by aario** [sabotage-linux/sabotage#561]
XML Parser perl module is required for xkeyboard-config to compile. Please add that to dependencies.
Also even after installing perl5-XML-Parser the error is still there making installation of xorg package impossible due to dependencies.

**Comment by aario** [comment]
Workaround: Modified the generated intltool-fake/intltool-perl to exit with 0 code when:
`if [ "$2" == "require XML::Parser" ]; then
exit 0
fi`
Therefore ignore this perl requirement!

**Comment by rofl0r** [comment]
thanks for the report, i could reproduce the issue.
