### ISSUE TITLE
Failed to build mesalib

### ISSUE THREAD

**Issue by aario** [sabotage-linux/sabotage#562]
The error is:
`unrecognized command line option -Werror=pointer-arith`
Only gcc-6 is currently installed on the system.

**Comment by rofl0r** [comment]
that's weird, my gcc 6.3.0 does understand `-Werror=pointer-arith`

can you post output of `gcc -v` and `gcc -Werror=pointer-arith helloworld.c` (writing helloworld.c is left as an exercise) ?

**Comment by rofl0r** [comment]
WORKSFORME. closing due to lack of OP collaboration.
