### ISSUE TITLE
xmms [fail] 

### ISSUE THREAD

**Issue by tankf33der** [sabotage-linux/sabotage#670]
fix deps
```
2019-12-07 12:49:19: start
2019-12-07 12:49:19: sourcing user defined optimization config /etc/butch-optflags.sh
2019-12-07 12:49:19: starting to untar
2019-12-07 12:49:19: untar done
2019-12-07 12:49:19: start build
patching file configure
patching file libxmms/configure
patching file xmms/util.c
patching file xmms/main.c
patching file General/ir/ir.c
patching file wmxmms/wmxmms.c
Package gtk+-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-2.0' found
```

**Comment by rofl0r** [comment]
thanks for report, but why don't you provide a PR? this should be easy enough to fix (if that's the only issue with the package, which i doubt)

**Comment by tankf33der** [comment]
> thanks for report, but why don't you provide a PR? this should be easy enough to fix (if that's the only issue with the package, which i doubt)

Sure, lets keep this shit broken like you did before.
I will not return.

**Comment by rofl0r** [comment]
xmms is a player that i liked a lot back in the day, unfortunately it's requiring gtk-1.0 and i spent a lot of effort to get it to work with gtk-2.0. IIRC i got it to compile, but never quite working right. i mainly left the package in the tree so someone willing to work on it can already start from an "it compiles" state.
