### ISSUE TITLE
http://ftp.barfooze.de/ doesn't respond

### ISSUE THREAD

**Issue by paul-cpp** [sabotage-linux/sabotage#697]
Hello, ftp.barfooze.de doesn't respond. How to fix it?

**Comment by rofl0r** [comment]
loads for me. still having issues ?

**Comment by paul-cpp** [comment]
Works good right now, but as I understand, it is periodically unavailable.
It would be great to use http://mirrors.2f30.org/sabotage/tarballs/ as a backup link if ftp.barfooze.de doesn't respond

**Comment by rofl0r** [comment]
> It would be great to use http://mirrors.2f30.org/sabotage/tarballs/ as a backup link if ftp.barfooze.de doesn't respond

yes indeed, that's why the mirror exists. but where do you mean it to be used ? from packages pointing to barfooze ? i believe they all point there already or am i missing something?

**Comment by paul-cpp** [comment]
Hi. it doesn't matter, now it works. Thanks
